#! /bin/sh
### BEGIN INIT INFO
# Provides:          thermronstat
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage my thermostat
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
export THERMOSTAT_HOME=/var/local/thermostat

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
      log_begin_msg "Starting thermronstat"
      # do something
      /var/local/thermostat/run.sh
      log_end_msg $?
      exit 0
      ;;
  stop)
      log_begin_msg "Stopping thermronstat (And all JAVA processes)"
      # do something to kill the service or cleanup or nothing
      /var/local/thermostat/kill.sh
      log_end_msg $?
      exit 0
      ;;
  restart)
      log_begin_msg "Restarting thermronstat"
      /var/local/thermostat/kill.sh
      /var/local/thermostat/run.sh
      log_end_msg $?
      exit 0
  
      ;;
  *)
      echo "Usage: /etc/init.d/<your script> {start|stop}"
      exit 1
      ;;
esac
 